### ISSUE TITLE
Heart rate and calories on watch stuck at 0

### ISSUE THREAD

**Issue by dieterstemmet** [Rexios80/Health-Data-Server-Overlay#10]
Don't think this is an issue with the server, it's most probably with the app on the watch. It might not have access to the data it needs or something. See attached screenshot.
![image](https://user-images.githubusercontent.com/20297027/85223892-eac10100-b3f8-11ea-966d-611d846bbd36.png)

Also getting this when running the app. Seems like the websocket connection can't be established (not sure if this is related):
# node ./public/app.js
Listening at port 8080
(node:16564) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (C:\Users\diete\Downloads\Health-Data-Server-Overlay-3.0\Health-Data-Server-Overlay-3.0\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:16564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Client connected

This is what gets served:
![image](https://user-images.githubusercontent.com/20297027/85223936-3bd0f500-b3f9-11ea-9f92-860b07da08da.png)

Please assist, and let me know where I can help.

Thanks
Dieter

**Comment by dieterstemmet** [comment]
If anyone faces this same issue, it's permissions related. Go to your iPhone Settings > Health >Data > Health Data Server and switch on read and write permissions from there.

**Comment by Rexios80** [comment]
The server app spits out that error when it can't connect to a local Discord instance. I should probably consume that error somewhere so the user doesn't see it.
