### ISSUE TITLE
Unable to install app on watchOS 7 beta

### ISSUE THREAD

**Issue by MEANCreek24** [Rexios80/Health-Data-Server-Overlay#11]
When I go to my purchased apps on the App Store (within the watch) I can download any other app but when I try to download “Health Data Server” it comes up with a message that says “downloading item, when this item is finished downloading it will be available in your library” and then I click okay and the download is canceled. I have tried everything, even factory resetting the watch

**Comment by Rexios80** [comment]
What iOS/watchOS versions are you on?

**Comment by MEANCreek24** [comment]
I’m on watchOS 7

**Comment by Rexios80** [comment]
I thought that might be the case. Unfortunately I can’t help you with beta software. And watchOS betas are especially nasty with bugs because you can’t downgrade back to the stable version.

**Comment by MEANCreek24** [comment]
Yeah I tried factory resetting it even and that didn’t downgrade, I do feel that it’s the app though because I can still download other apps on the watch it’s just health data server that I can’t download unfortunately. Are there any other people with this issue?

**Comment by Rexios80** [comment]
Are those other apps standalone watch apps or do they have a companion iPhone app?

**Comment by MEANCreek24** [comment]
They have been ones with a companion iPhone app, I looked for some stand alone but I couldn’t find any other than this one

**Comment by Rexios80** [comment]
This may be related to the removal of Force Touch in watchOS 7. Even if this isn't the issue, I still need to move the context menu buttons somewhere else.

**Comment by Rexios80** [comment]
I released a new version that does not use the Force Touch menu. Can you try installing it on watchOS 7 again?

**Comment by MEANCreek24** [comment]
Yes thank you so much I’ve got it up and running now your app works a treat!!

**Comment by Rexios80** [comment]
Awesome! You don't have to, but it would really help me if you left a review on the App Store page. Thanks for helping me find this issue.

**Comment by MEANCreek24** [comment]
I will review right now thank you again!
