### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by falibu** [Rexios80/Health-Data-Server-Overlay#12]
hello. i've been using HDS for a few weeks and have loved it as it's mostly worked with exception to a few user error related sessions. however, lately i've been having trouble getting heart data to show up on the watch UI and eventually it times out and needs to be restarted. the executable just stays at connected but no numbers are generated on the watch, the app or any of the overlays i try. i'm pretty sure everything is connected properly because sometimes it works.

from time to time, it will "unclog" and push through but i've not been able to recreate how i get it working when it does work.

love the software for my twitch stream. please advise :D

**Comment by Rexios80** [comment]
Did you try force quitting the app on the watch?

https://9to5mac.com/2018/09/27/how-to-force-quit-apple-watch-apps/

**Comment by falibu** [comment]
i thought i did but after reading that article, it turns out i was not properly force quitting the app. i'm still new with my apple watch so thanks for that. however, i did attempt to reset my router, my phone, and my watch multiple times with no noticeable difference. would resetting the watch have a lesser effect than force quitting the app? asking out of curiosity. 
thanks for your time and i'll report back either way :D

**Comment by falibu** [comment]
on a brighter note, right now it is working after being spotty for the last two days. will attempt the force quit solution if it decides to clog up again. thanks so much :D

**Comment by Rexios80** [comment]
If by "reset" you mean "restart" then it's possible that the app could still be in cache somewhere and not fully dead. Force quitting the app like that makes sure it is actually dead.
