### ISSUE TITLE
Server doesn't pick up data health data after latest Watch update

### ISSUE THREAD

**Issue by dieterstemmet** [Rexios80/Health-Data-Server-Overlay#13]
Hi,

Everything was working cool, up to right after I updated my watch. Tried reinstalling the app on the watch, multiple phone and watch reboots, port changes etc.

Looks like the watch correctly reports heart rate, but it doesn't seem to get to the server. Not seeing any of those printouts indicating heart rate and calories.

Any ideas?

KR
Dieter

**Comment by Rexios80** [comment]
What watchOS version?

**Comment by dieterstemmet** [comment]
v6.2.6 (17T620)

**Comment by Rexios80** [comment]
Are you sure the watch is on the same network as the server?

**Comment by dieterstemmet** [comment]
Yes. Will see if I can forget and reconnect to the network, haven't tried that yet.

**Comment by dieterstemmet** [comment]
Yeah still the same. iPhone, watch and server on the same network.

**Comment by Rexios80** [comment]
Maybe try disconnecting the watch from the phone and using WiFi directly

**Comment by dieterstemmet** [comment]
Tried that as well.

**Comment by Rexios80** [comment]
You’re sure nothing else changed? I’m running 6.2.6 on my watch and it works fine. Maybe try opening the port in your Windows firewall.

**Comment by dieterstemmet** [comment]
Let me try that.

**Comment by dieterstemmet** [comment]
Okay, looks like it was a firewall issue, thanks! Also, thanks for the prompt feedback, and a really useful app.

**Comment by Rexios80** [comment]
Yeah no problem! I should probably make an FAQ.

**Comment by dieterstemmet** [comment]
Good idea!

**Comment by dieterstemmet** [comment]
In this specific case my network seems to have changed from a private to a public network (for some odd reason :|). The inbound firewall rules were set up to allow the Node.js: Server-side JavaScript on private networks (which is why it worked before), but not on public networks, so just had to enable it for public networks as well.
