### ISSUE TITLE
Only get "-" shown.

### ISSUE THREAD

**Issue by mcnstr** [Rexios80/Health-Data-Server-Overlay#14]
When I follow the steps i cant get the localhost:8080 or the command window to show anything but "-" or "Client connected" when i refresh the localhost.

Ive tried both on a Windows 10 and a MacOS-computer, both on different networks. Same results.
Manually opened the port 8080 in the windows firewall.

WatchOS: 6.2.6
iOS: 14.0

**Comment by Rexios80** [comment]
Are you sure you're using the right IP address on the watch app? I just tried setting up the application from scratch and it works for me, so it has to be something with your configuration.

**Comment by mcnstr** [comment]
> Are you sure you're using the right IP address on the watch app? I just tried setting up the application from scratch and it works for me, so it has to be something with your configuration.

Yes, double checked on both locations(home(win10) + work(macOS), same results.

**Comment by Rexios80** [comment]
I just tried it fresh on macOS as well and it works as expected.

Can you send me the exact text you're entering into the watch app? The only issue could be either that or your network configuration.

**Comment by mcnstr** [comment]
192.168.86.53:8080

Im gonna try to reinstall both the app and set it up again on windows!

**Comment by mcnstr** [comment]
> 
> 
> 192.168.86.53:8080
> 
> Im gonna try to reinstall both the app and set it up again on windows!

No luck!

**Comment by Rexios80** [comment]
You don't have a VPN or anything do you? Are you absolutely sure the watch is on the same network as the computer? Did you try disconnecting the watch from the phone and using WiFi directly?

If you try all that, you're sure the port is open, and you're sure the IP address is correct I might be out of ideas. The app definitely works, there's just something weird with your network setup.

Also the watch app is showing your current heart rate and calories, right?

**Comment by mcnstr** [comment]
Tried without VPN also, but everything works fine, its just the connection between the app and the pc, so its probably some weird configuration on the networks as you say, not the app :)

Thanks for the help anyway!

**Comment by j1654w** [comment]
Hey mcnstr, hoes you solve this issue??  Experiencing the same thing

**Comment by mcnstr** [comment]
> Hey mcnstr, how’d you solve this issue?? Experiencing the same thing

I havent solved it yet, still working on it :) Im guessing its a network problem on my home network, and maybe my network at work have some built in VPNs or closed ports

**Comment by mcnstr** [comment]
So I got it to work, my wired and wireless network was identified as two different networks for some reason. Fixed that and now it works flawlessly.
