### ISSUE TITLE
Config file causes application to crash

### ISSUE THREAD

**Issue by XrayXout9** [Rexios80/Health-Data-Server-Overlay#16]
**Hardware/Software**
- iPhone: 11
- iOS: 14 beta 4
- Apple Watch: series 3 38MM
- watchOS: 6.2.8
- Windows: no idea it's hard to find it
- App: app doesn't say either
- Server: latest (doesn't say in application)

creating a config.json file cause the server app to crash repeatedly.
i copy-pasted the example text from the github and changed the port from 8080 to 8081 bc something is already running on 8080 on my network.

**Comment by Rexios80** [comment]
Your config file looks exactly like this?
```
{
  "httpPort": 8081,
  "websocketPort": 3476,
}
```

**Comment by Rexios80** [comment]
Uh oh that last comma isn't supposed to be there. My bad. Make it look like this and it shouldn't crash:
```
{
  "httpPort": 8081,
  "websocketPort": 3476
}
```

**Comment by Rexios80** [comment]
I also fixed this in the README

**Comment by XrayXout9** [comment]
yes it has worked now. thank you!

**Comment by Rexios80** [comment]
Awesome! If you want to could you please leave a review on the App Store once you have enough experience with the app?
