### ISSUE TITLE
Can't execute HDS-Overlay-win.exe

### ISSUE THREAD

**Issue by renenm** [Rexios80/Health-Data-Server-Overlay#17]
Hi,

I can't execute HDS-Overlay-win.exe, nothing happens when Im running it with administration priviliges. Nothing happend.

Windows 10 Pro 1903@ x64
Intel i7-75000 

Thank you.

**Comment by Rexios80** [comment]
Run it from the command line. There is probably an error you can't see because it closes too fast for you to be able to see it.

**Comment by Rexios80** [comment]
Or try running the new version I just released that should prevent the application from closing instantly when there is an error

**Comment by renenm** [comment]
> Run it from the command line. There is probably an error you can't see because it closes too fast for you to be able to see it.

This was the answer! Thank you for your fast reply and the app!

**Comment by Rexios80** [comment]
If you enjoy the app please consider leaving a review on the app store. Thanks for your support!
