### ISSUE TITLE
Since its packaged now.. how do I edit...

### ISSUE THREAD

**Issue by beaudamion** [Rexios80/Health-Data-Server-Overlay#18]
Quick couple questions since it's packaged now.
1. How do I replace the connect/disconnected image. I changed the class but didn't seem to change the image. 
2. I originally added text after the heart rate number... How can I add this now?
3. Since this is using websocket could I pull this line into say Reselim's beat-saber-overlay via html / css if I added it as a row in that overlay?
4. any way to support netbios / wins to connect by computer name? streaming on different networks I usually have to update the ip on the watch.. just an extra step.
5. whats the native resolution for the overlay / space wise.. is it absolute or is the div just adjusting to fit.

Love the app / overlay been super awesome! Thank you!

**Comment by Rexios80** [comment]
1. The image that shows when the watch is disconnected probably isn't configurable right now. You could change the size or hide it, but that's about it.
2. Add this to the Custom CSS in OBS `.hr::after { content: "bpm" }`
3. Probably not without writing code
4. You can use something like [ZeroTier](https://www.zerotier.com) to set up a VLAN so you can use the same IP address everywhere
5. The resolution is not absolute. You can change the image/font sizes if you want it to be high quality at larger sizes.

**Comment by beaudamion** [comment]
Thanks for the quick response!
as for 3.. I'll see if I can just iframe it as the overlay is local. 

Thanks again for all your work.. super awesome app.
