### ISSUE TITLE
Overlay does not update.. stuck on loading overlay.

### ISSUE THREAD

**Issue by beaudamion** [Rexios80/Health-Data-Server-Overlay#19]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes/No (If you say no please provide an explanation)
Yes

**Hardware/Software**
- iPhone: ex: 11 Pro 
- iOS: ex: 13.6.1
- Apple Watch: ex: Series 5 44mm wifi
- watchOS: ex: 6.2.8
- Windows: ex: Windows 10 2004
- App: ex: 4.1
- Server: ex: 6.2.1

**To Reproduce**
Turn on and connect
window gets heart and calorie data
go to local host website... no info updates

**Additional context**
Just randomly stopped working. doesn't update the overlay enven though the app shows its getting data.

**Comment by Rexios80** [comment]
So you had it working before? Did anything with your network setup change?

**Comment by beaudamion** [comment]
It was working... Ran it said there was an update.. got your latest release and overwrite the old version in my folder. loaded it up and it worked... restarted computer loaded up again to stream and now the overlay doesn't update. stuck on the connecting image.  the app on watch is connected.. the window on computer is showing calories and heart rate data. The overlay in browser doesn't update.

**Comment by Rexios80** [comment]
Are you using a custom config file? The latest update has a new config option that must be included if you are using a config file. The behavior you're seeing seems like what would happen if you did not include the new config option.

**Comment by beaudamion** [comment]
Sigh... Please disregard.. I am an idiot... I should probably read before updating things.

Again great app.

**Comment by Rexios80** [comment]
Maybe I should make the application crash if you don't specify the new option to make it more obvious. But anyways I'm glad you got it figured out.

**Comment by Rexios80** [comment]
The app now crashes with a helpful message if the websocketIp field is not specified in the config file
