### ISSUE TITLE
An option to do not save as « Exercices »

### ISSUE THREAD

**Issue by LioLynf** [Rexios80/Health-Data-Server-Overlay#2]
Hello !! Amazing app, thank you !!
Is it possible to add an option to not save as an exercice, in order to not affect my exercice ring.
Many thanks !

**Comment by LioLynf** [comment]
(Uncheck the box « Exercices » in Setting > Health > Access on data and devices > Heart Data Server doesn’t help : the data server on the watch won’t launch)

**Comment by Rexios80** [comment]
I tried to add this as a feature but I was having issues. I didn’t think about implementing it that way. I’ll try again when I get time.

**Comment by LioLynf** [comment]
I understand. Thanks anyway !

**Comment by Rexios80** [comment]
So I think I figured out how to implement this feature. I hope to have an update with a "Save to Apple Health" toggle and a selector for what workout to save it as pushed by next week.

**Comment by Rexios80** [comment]
I just submitted a version 2.0 update that adds a toggle for this. It should be approved within a few days. Let me know how it works for you.

**Comment by LioLynf** [comment]
Thanks a lot for your time to check it out. Will make you a feedback

**Comment by LioLynf** [comment]
Works like a charm !! Thanks you very much !!! :D
