### ISSUE TITLE
Purchased app, cannot download 

### ISSUE THREAD

**Issue by antlepore** [Rexios80/Health-Data-Server-Overlay#20]
Title is the problem - payment went through

**Comment by Rexios80** [comment]
Download it from the App Store on the watch itself

**Comment by antlepore** [comment]
Same issue there as well

**Comment by Rexios80** [comment]
What watch and watchOS version are you using?

**Comment by antlepore** [comment]
Series 3 and most updated version

**Comment by Rexios80** [comment]
What does it do when you try to download it?
