### ISSUE TITLE
Not sending data to Localhost:8080 (and random force touches with symbol on Apple watch)

### ISSUE THREAD

**Issue by SammyBTTV** [Rexios80/Health-Data-Server-Overlay#21]
Hi there!
I just purchased this app from the app store to help me with putting my heartrate on stream from my Apple watch. I'm not 100% tech literate but I know a fair bit. I've connected the IP address of my computer to the watch (including the port), ran the latest .exe, even installed node.js (which you shouldn't need to do on the more recent versions). I just can't get the watch to send any data at all. It seems to just show the same image as it did when I first connected to localhost:8080. 

There's random force-touches coming through on my apple watch too whenever I start the program's monitoring (which is really annoying), along with a crossed-out yellow lightning symbol next to my heartrate on the watch app.

I havent tried many in-depth troubleshooting steps, but I'd really appreciate any help on this one! Thank you so much in advance :)

**Comment by Rexios80** [comment]
The random force touches sounds like a hardware issue with your watch. As for the connection issues, did you try any of these troubleshooting steps: https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting

**Comment by SammyBTTV** [comment]
Hi there! Thanks for the response.

I’ve been trying to get the application to work for about 2 weeks not; this is the first time I’ve experienced the force touches and the logo beside the heart rate beats per minute on the interface. I just can’t believe that is a coincidence, but then again, there’s always the possibility I guess. The force touches only happen within the app, and while the monitoring is active, that’s why I’m thinking its trying to send me some kind of error message.

Regarding the troubleshooting steps, I’ve followed all the steps from Apple, including checking for updates on the watch (there were no updates), shutting down the watch and shutting down the app. Even though I understand tech a little, I’m reluctant to do anything regarding an ‘inbound port’ in Windows, just because I don’t fully understand what it might do and its consequences affecting my PC. Is there any chance you could give  me a little information about it, and guide me through?

Thanks so much guys, sorry to be such a hassle!
Sammy B :)

**Comment by Rexios80** [comment]
The app makes the watch vibrate when it cannot connect to the server. The vibrations might be making the force touch issue happen, but the app certainly isn't making the force touches happen on purpose.

If you've tried everything else, then opening the port in your firewall is probably the solution. The only way I can see opening the port could be unsafe is if someone knows the port is open, is inside your network, and already has a malicious program running on your computer that is listening at that port. In other words, it's safe to do so. Your router does most of the protection regarding open ports. The Windows Firewall is a last defense just to be extra safe.

Also make absolutely sure that your phone/watch and the computer running the server are on the same network. Some routers automatically create "guest" networks or something similar which are unable to communicate with each other.

**Comment by Rexios80** [comment]
If you need any more help let me know
