### ISSUE TITLE
App immediately closes when trying to open on watch

### ISSUE THREAD

**Issue by ddemcee** [Rexios80/Health-Data-Server-Overlay#22]
Hi there! The app on my apple watch doesn't seem to be working.  I've purchased and downloaded it to my apple watch (series 3) and when I try to open the app on the watch it immediately closes.  The watch is running on version 6.2.8 of the ios.  I haven't downloaded the latest version 7.0 yet.  Is that the issue?  Or is there something else I can fix?  Thanks in advance for your help.

**Comment by Rexios80** [comment]
That's definitely weird. My only suggestion right now is to install watchOS 7. If that doesn't work I can try and help you further.

**Comment by Rexios80** [comment]
If you need any more help let me know

**Comment by ddemcee** [comment]
After I updated my watch to the new iOS, it fixed the issue.  And the app works great so far!  Thank you!

Love: Daniel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
