### ISSUE TITLE
Apple Watch Unable To Connect to PC Server

### ISSUE THREAD

**Issue by phobosd** [Rexios80/Health-Data-Server-Overlay#25]
Hello we are having issues connecting the watch to the server. Getting the error image when pulling up the :8080 site on the PC, and the connection error shows on the watch app.

We have tried: 
Disabled Firewalls/Windows Defender/etc
Disabled anti virus
Tried both version of the server on the PC
Wireshark'd tcp port 8080, got no results
Verified that the PC and Watch are on the same subnet/no filtering/no segmentation

Does the phone app come into play here if the watch is connecting to wifi? The PC can ping the iphone, and vice versa. '

Please advise, thank you!

**Comment by Rexios80** [comment]
The connection is routed through the phone unless the watch is completely disconnected from the phone

**Comment by phobosd** [comment]
The phone and computer can ping each other, but we're not seeing requests coming into tcp 8080 on the PC from anywhere, which is the larger issue I believe. We will look at the watch and see if it's connected to the phone in any way and if it is, narrow it down from there.

**Comment by Rexios80** [comment]
Did you ever resolve this?

**Comment by Rexios80** [comment]
If you need more help let me know.
