### ISSUE TITLE
Health Data Server app not appearing on Apple Watch 

### ISSUE THREAD

**Issue by BostonsLegend** [Rexios80/Health-Data-Server-Overlay#26]
Hello, I’m experiencing the issue where the Health Data Server app is not appearing on my Apple Watch, although it’s been purchased. I’ve tried restarting my watch, my iPhone, and it still is not giving me the option to download the app to my watch. Has anyone experienced this before? watchOS is 7.0.1

**Comment by Rexios80** [comment]
Are you trying to download it from the App Store on the watch and not the phone?

**Comment by BostonsLegend** [comment]
So when I view the app on my phone, it just shows as “Purchased” (Grayed out) with no option to install. When I go to the watch, the app does not appear there either.

**Comment by Rexios80** [comment]
There is an App Store ON the watch. You have to install it from there.

**Comment by BostonsLegend** [comment]
Ah. Got it! My apologies. Still new to the watch game! Thanks so much.
