### ISSUE TITLE
Apple Watch not connecting

### ISSUE THREAD

**Issue by mheroanki** [Rexios80/Health-Data-Server-Overlay#28]
Not sure what to do or what screenshots to show. 

I opened the exe, connected my apple watch to my IPv4 address through the HDS app(including the :8080), and it's simply not connecting.

**Comment by Rexios80** [comment]
Are you using server version 7.0.0?

**Comment by mheroanki** [comment]
> Are you using server version 7.0.0?

of the HDS Overlay? yes

**Comment by Rexios80** [comment]
Make sure your watch app is on version 5.0 as well. You should be able to get the update on the App Store on the watch. Don't put the port in the watch app anymore unless you changed it in the config file. Read the release notes for the new server version they should help you.

**Comment by mheroanki** [comment]
Ah, got it. I just had to remove the port. Thank you!
