### ISSUE TITLE
purchased app/ shows unpurchased after watch update

### ISSUE THREAD

**Issue by clickfornif** [Rexios80/Health-Data-Server-Overlay#29]
used the app fine for a couple months. with the last OS update i had to reset my watch and now the watch app store tells me i need to purchase instead of letting me redownload. App store on my phone says already purchased.

**Comment by Rexios80** [comment]
Did you restart your watch?
Try force quitting the App Store on the watch. 
What happens if you press the purchase button but don't actually complete the transaction?
Maybe try resetting your watch again?
If those don't work you'll have to contact Apple support. I can't fix App Store issues as frustrating as that is.

**Comment by Rexios80** [comment]
Did you get this figured out?

**Comment by clickfornif** [comment]
sadly not. I tried your suggestions to no avail. Contacted the Apple support but they are the worst support service i ever experienced. I should get a phone call from an 'expert' tomorrow to see what more they can try. It's a synchronization error between the 2 devices app stores it seems they just don't know how to fix it

**Comment by Rexios80** [comment]
I'm so sorry I can't help you. Apple _really_ needs to improve the App Store experience for standalone Apple Watch apps. It's a mess right now and it seems like they just don't care.

**Comment by clickfornif** [comment]
i'll get it sorted out eventually. will not give up that easy! At some point there has to be a competent person on the other side of the support line right ?

**Comment by Rexios80** [comment]
I think we need competent developers more than competent customer service, but I hope you can get it fixed.

**Comment by Rexios80** [comment]
I made an iOS app that should help you install the watch app if you were having issues. Let me know if it works.
