### ISSUE TITLE
Use Hostname not IP address in watch app

### ISSUE THREAD

**Issue by wlvstv** [Rexios80/Health-Data-Server-Overlay#3]
firstly, incredible work! I was hoping I could use a hostname and not an IP address in the app. I am using a lambda endpoint that I am sending the data to for processing and the ip is not static. Any thoughts on how I could solve for this?

Thanks again!

**Comment by Rexios80** [comment]
Did you try it? I would think it might just work. The code doesn't require it to be an IP address, that's just what most people would put in there.

**Comment by wlvstv** [comment]
I have been trying it but no success, not sure the format I need to use, if I need to still include a port, or include the https:// before the hostname. as I understand the app is sending a POST to the endpoint but I haven't seen any traffic making it through.

**Comment by Rexios80** [comment]
Oh I hardcoded "http://" into the app so if you need "https://" then it probably wouldn't work. I could work on this if it's useful for you.

**Comment by wlvstv** [comment]
let me see if I can force an upgrade on it or something

**Comment by Rexios80** [comment]
I'm not sure what you mean. I'm pretty sure I would have to remove the hardcoded "http://" in order for this to work for you.

**Comment by wlvstv** [comment]
sorry, i meant on my end, I can try to allow it to work over http!

**Comment by Rexios80** [comment]
Alright. If you can't get it to work let me know and I'll work on having that part not hard coded.

**Comment by wlvstv** [comment]
I was able to get it to work by building an http proxy in front of it. It would be a great feature to allow https support moving forward. let me know if I can help, would love to submit a PR

**Comment by Rexios80** [comment]
The watch code isn’t public. It’s a really simple fix I just need to implement and test it.

**Comment by wlvstv** [comment]
All good, please let me know if you need someone to test or anything, happy to help in any way!!

**Comment by Rexios80** [comment]
I'll probably set up a TestFlight so we can test with that. I should have time to get it set up tonight.

**Comment by Rexios80** [comment]
Just wanted to update you. I submitted a change that should allow you to do what you want to TestFlight. As soon as I get it approved I'll set you up with a link to join the test.

**Comment by Rexios80** [comment]
Here's the TestFlight link. Let me know how it goes using https natively within the app.

https://testflight.apple.com/join/hG4FkmZ4

**Comment by Rexios80** [comment]
I've been using this version for a few days and it seems fine for normal use, so I just released it to the public. I don't have a way to test your use case, so when you get a chance to test this let me know how it goes.
