### ISSUE TITLE
Not sending info from watch 

### ISSUE THREAD

**Issue by EPICSMASHER1** [Rexios80/Health-Data-Server-Overlay#32]
Yes, I tried the trouble shooting. 

I have everything up but it is not sending info

 [
![IMG_6376](https://user-images.githubusercontent.com/72764145/95785216-59c1ae80-0ca3-11eb-959a-f2dd67364321.jpg)
](url)

**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes/No (If you say no please provide an explanation)

**Hardware/Software**
- iPhone: ex: 11 Pro Max
- iOS: ex: 13.5.1 (if you are on a beta please specify)
- Apple Watch: ex: Series 5 44mm LTE
- watchOS: ex: 6.2.6 (if you are on a beta please specify)
- Windows: ex: Windows 10 2004 (if you are on a beta please specify)
- App: ex: 2.1
- Server: ex: 3.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Rexios80** [comment]
What did you put in the IP Address field in the setting page?

**Comment by chickensaladsandwhich** [comment]
im having this same issue, ive entered everything correctly

**Comment by Rexios80** [comment]
Did you add anything to the IP address? You're not supposed to any more unless you changed the port

**Comment by chickensaladsandwhich** [comment]
i didn’t add anything to the ip address, but i did change the port. am i
supposed to add the 3476 since i did change port?

**Comment by Rexios80** [comment]
Please read the release notes for the server. You need to use the websocket port now. If you did not change the websocket port, you do not need to include it in the settings page.

**Comment by EPICSMASHER1** [comment]
How do I get the default up address 


Sent from Yahoo Mail for iPhone


On Monday, October 12, 2020, 4:10 PM, Rexios80 <notifications@github.com> wrote:




What did you put in the IP Address field in the setting page?

**Comment by Rexios80** [comment]
https://www.tp-link.com/us/support/faq/838/

Not sure if this is what you're asking, but here

**Comment by Rexios80** [comment]
Server version 7.2.0 lists possible IP addresses on startup. Maybe that will help you.

**Comment by EPICSMASHER1** [comment]
Thank you I’m gonna try tonight just got off of work. 


Sent from Yahoo Mail for iPhone


On Wednesday, October 14, 2020, 7:58 PM, Rexios80 <notifications@github.com> wrote:




Server version 7.2.0 lists possible IP addresses on startup. Maybe that will help you.

**Comment by Rexios80** [comment]
Did the new server version help at all?

**Comment by EPICSMASHER1** [comment]
No it did not work I tried deleting and re installing but it won’t let me re install how do o do that?


Sent from Yahoo Mail for iPhone


On Thursday, October 15, 2020, 10:49 AM, Rexios80 <notifications@github.com> wrote:




Did the new server version help at all?

**Comment by Rexios80** [comment]
You tried reinstalling what? If you're talking about the watch app make sure you're installing it from the App Store app that is on the Apple Watch

**Comment by EPICSMASHER1** [comment]
I tried installing the health app on my watch but it just says purchased doesn’t give the ability to re download.  I sent a photo for you. I don’t know what to do. 


Sent from Yahoo Mail for iPhone


On Friday, October 16, 2020, 10:53 AM, Rexios80 <notifications@github.com> wrote:




You tried reinstalling what? If you're talking about the watch app make sure you're installing it from the App Store app that is on the Apple Watch

**Comment by Rexios80** [comment]
There is an App Store app ON THE WATCH that you have to use to download the app. It will not work from the App Store on the iPhone.

**Comment by Rexios80** [comment]
There's no image showing in your replies

**Comment by EPICSMASHER1** [comment]
I understand, The snap shot is from the watch.



Sent from Yahoo Mail for iPhone


On Friday, October 16, 2020, 3:00 PM, Rexios80 <notifications@github.com> wrote:




There is an App Store app ON THE WATCH that you have to use to download the app. It will not work from the App Store on the iPhone.

**Comment by Rexios80** [comment]
What watchOS version are you on? If you're on watchOS 6 can you try updating to watchOS 7?

**Comment by Rexios80** [comment]
Did you ever get this figured out?

**Comment by EPICSMASHER1** [comment]
Unfortunately no, I’m gonna do a factory reset on the watch so all apps are off then log in and download from cloud hopefully


Sent from Yahoo Mail for iPhone


On Thursday, October 22, 2020, 12:38 PM, Rexios80 <notifications@github.com> wrote:




Did you ever get this figured out?

**Comment by Rexios80** [comment]
Since your problem is with the App Store and not my app, I'm closing the issue for now. Feel free to reopen it if you need more help from me once you get the app actually installed.

**Comment by Rexios80** [comment]
I created an iPhone app that should allow you to get the watch app installed if you were having issues

**Comment by EPICSMASHER1** [comment]
Your a BOSS-E-BOSS Thankfully after the reset And your most current update 7.0It works amazing and I love the updated animation.Thank you so much I used it on my last stream so cool 😎 


Sent from Yahoo Mail for iPhone


On Friday, November 6, 2020, 12:05 PM, Rexios80 <notifications@github.com> wrote:




I created an iPhone app that should allow you to get the watch app installed if you were having issues
