### ISSUE TITLE
config.json crushing 

### ISSUE THREAD

**Issue by GoRnoStayStandin** [Rexios80/Health-Data-Server-Overlay#34]
App is crushing when I created this file. I putted it in public and it goes ok, but animation of heart is still going. How can I turn off this animation?
![SharedScreenshot](https://user-images.githubusercontent.com/57696403/96330208-248fd480-1086-11eb-87cb-1b88b0f25992.jpg)

**Hardware/Software**
- iPhone: ex: 11 Pro Max
- iOS: ex: 13.5.1 (if you are on a beta please specify)
- Apple Watch: ex: Series 5 44mm LTE
- watchOS: ex: 6.2.6 (if you are on a beta please specify)
- Windows: ex: Windows 10 2004 (if you are on a beta please specify)
- App: ex: 2.1
- Server: ex: 3.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Rexios80** [comment]
I'm assuming you got it figured out? If you need help changing the font I can help you with that.

**Comment by Rexios80** [comment]
I added a Custom CSS example to the README. Hopefully that can help you configure the overlay the way you want.
