### ISSUE TITLE
Having Trouble with IP Addresses

### ISSUE THREAD

**Issue by CooperHMan** [Rexios80/Health-Data-Server-Overlay#35]
I've read the tutorial on how to set the application up and connect it and everything but I'm having trouble with my IP address. It is just the default 192.168.1.2

I can't figure out how to change this. I've inputted it into my watch and then I click start and nothing pops up on my browser? Not sure how to fix this, I hope there's a simple solution.

**Comment by CooperHMan** [comment]
I believe I've done everything correctly it is literally just the IP address that won't connect. Just need a way to find the actual IP address and not this stupid default thing that doesn't work, very frustrating!

**Comment by Rexios80** [comment]
The IP addresses the overlays lists are just what your IP address _might_ be. It's not a guarantee that any of them will work. Are you on Windows? If so did you make sure to check both boxes in the Windows Firewall popup?

**Comment by CooperHMan** [comment]
Yeah mate I followed all the steps, I had a look at where to find my IP address and it only showed this one and when I wrote it into the Apple Watch app and started the activity, nothing happened.

**Comment by Rexios80** [comment]
Are you sure the Windows Firewall dialog came up? Sometimes it doesn't and the overlay won't work until you manually open the ports.

**Comment by CooperHMan** [comment]
Yeah it did, I can try again and see if it pops up! It’s very strange

**Comment by Rexios80** [comment]
Also make sure to try the troubleshooting steps if you haven't already: https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting

**Comment by Rexios80** [comment]
Did you ever get this figured out?

**Comment by Rexios80** [comment]
If you need more help let me know

**Comment by CooperHMan** [comment]
Honestly I just stopped with it, couldn't be bothered trying anymore. I spent hours and did everything right. Might be because of Australia? It was stupid, but thanks for your help.
