### ISSUE TITLE
Can't seem to get heart rate reading

### ISSUE THREAD

**Issue by catherine1603** [Rexios80/Health-Data-Server-Overlay#36]
Hi, I can't seem to get any heart rate reading from the app. And I'm not too sure what's that yellow lightning bolt with a strike is at the right side.
![121705523_699911547573669_1382832228097165801_n](https://user-images.githubusercontent.com/73063769/96367425-59805200-1180-11eb-988b-520afa7fcf7c.jpg)

**Comment by Rexios80** [comment]
That means it's disconnected. Did you try the troubleshooting steps?

**Comment by edofthefu** [comment]
I had this issue until I realized I needed to delete the port from the settings on the watch following one of the recent updates.  I hadn't been aware until I read through several of the other issues on GitHub.

**Comment by Rexios80** [comment]
Did you ever get this figured out?

**Comment by Rexios80** [comment]
If you need more help let me know
