### ISSUE TITLE
Feature request: accelerometer data

### ISSUE THREAD

**Issue by manualmanul** [Rexios80/Health-Data-Server-Overlay#37]
Hi! Great app, does almost everything I need. I was wondering, could you please implement sending the watch's accelerometer/movement data to the server? I'd like to be able to tell whether I'm sitting at my desk or actively moving. Best regards.

**Comment by Rexios80** [comment]
I guess I could see the argument that accelerometer data is "health data". As long as you're not expecting me to do anything with the data for you in the overlay then I'll think about implementing it sometime soon. I'm working on adding more configurability to the watch app anyways, so it would fit within those updates.

**Comment by manualmanul** [comment]
Of course, I'll be using my own websocket client to receive and process that data. Thank you for considering it!

**Comment by Rexios80** [comment]
Is sending the processed motion data okay? https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data

Also how frequently do you want the data? I think it gets generated 60 times a second, but that sounds like way too much. Is once a second okay?

**Comment by Rexios80** [comment]
Maybe 5 times a second I'm not sure how much you need

**Comment by Rexios80** [comment]
Or maybe I could make that configurable too

**Comment by manualmanul** [comment]
Processed data looks like it would work, and as for frequency, I think sending an average of 60 samples over 1 second would be better. I'm worried that sending that many updates would impact battery life too much

**Comment by manualmanul** [comment]
I've read the documentation link that you've provided a bit more, looks like what I'm looking for is `userAcceleration` property of `CMDeviceMotion`. Also, 60 samples may be a bit much now that I think about it. Can you add an option so that the app samples the data 30 times for every second that the user specifies and then sends the result?

**Comment by Rexios80** [comment]
Do you mean that you want to be able to configure the number of seconds the 30 samples are averaged from? Like you could average 30 samples over 1 second, or 30 samples over 2 seconds, etc?

**Comment by manualmanul** [comment]
Well, I meant that the sampling rate would scale using a formula like `amountOfSeconds * 30` and the averaged result would be sent to the server after `amountOfSeconds`

Sorry if I’m explaining this poorly, I know this is a very specific request and I appreciate your patience with me

**Comment by Rexios80** [comment]
Ohhh I get it. You always want 30 samples a second, but to be able to configure the number of seconds the app waits before averaging the samples and sending them.

**Comment by manualmanul** [comment]
Yes, exactly :)

**Comment by Rexios80** [comment]
How's this?
https://imgur.com/a/RgXyjY4

**Comment by Rexios80** [comment]
Wait it's putting some garbage in the output let me fix that

**Comment by Rexios80** [comment]
Here we go: https://imgur.com/a/TxV0x0k

**Comment by Rexios80** [comment]
You can toggle collecting motion data on and off and also select an output interval of anywhere between 1 and 30 seconds

**Comment by manualmanul** [comment]
I'm guessing those are 3-axis acceleration values? If that's the case, this appears to be exactly what I wanted! Thank you for implementing this so quickly 👍

**Comment by Rexios80** [comment]
Yeah it's [x,y,z]. I can't promise when the update will be out but at least the feature is in there.

**Comment by Rexios80** [comment]
It was the easier of the two features I wanted to implement so I just did it first

**Comment by Rexios80** [comment]
The watch app update with this feature included just got released. Let me know if it works for you.

**Comment by Rexios80** [comment]
Since the feature is added, I'm closing the issue for now. Let me know if you have any issues with the motion data.

**Comment by manualmanul** [comment]
Hi,

Sorry, was really busy so I couldn't test this properly until now. I'm not able to turn on the "Motion data" switch in settings. This is happening both after updating and after reinstalling the app. Let me know if there's something that I can do to help troubleshoot this

**Comment by manualmanul** [comment]
Nevermind, it took a few minutes but it turns on now. My websocket client isn't receiving any motion data though, will do more testing and let you know if it works shortly.

**Comment by Rexios80** [comment]
Super weird you couldn't turn the switch on. I've never seen it be troublesome. I just tested again and my websocket clients are getting the motion data.

**Comment by manualmanul** [comment]
Yeah, the switch for motion seems really finicky about where I tap to turn it on, no idea what's up with that.

As for motion, nothing that I've tried seemed to work. I'll try resetting the watch to factory defaults. I'm using an Apple Watch S2 with watchOS 6.2.8 btw.

**Comment by Rexios80** [comment]
Do the other switches work fine? There shouldn't be anything different about the motion switch.

**Comment by Rexios80** [comment]
Also does the switch stay on after you leave the settings page and come back?

**Comment by manualmanul** [comment]
Factory resetting seems to have fixed the switch issue. Yes, it stays on after leaving and returning, including after force-closing the app.

However, I'm still not receiving any motion data even after turning on the motion data switch. I'm only receiving heartRate, calories and hrColor. Can I do anything to help troubleshoot this?

**Comment by Rexios80** [comment]
This is really weird. Do you have any way to verify that the sensor in your watch is working?

**Comment by manualmanul** [comment]
Well, raise to wake works, and that relies on the accelerometer and gyroscope as far as I know.

Can you share a test app that would use your function that retrieves accelerometer data? I can try side-loading it locally using Xcode and checking what the problem is that way.

**Comment by Rexios80** [comment]
Does this work? I've never built an ipa before.
[CoreMotionTest WatchKit App.ipa.zip](https://github.com/Rexios80/Health-Data-Server-Overlay/files/5440612/CoreMotionTest.WatchKit.App.ipa.zip)

**Comment by Rexios80** [comment]
Also if we could talk on Discord that would be a lot easier.
Here is the support server if you're interested: https://discord.gg/FayYYcm
