### ISSUE TITLE
Need help with App

### ISSUE THREAD

**Issue by jfantv** [Rexios80/Health-Data-Server-Overlay#39]
Hi,

I can't figure out how to turn off the heart rate animation using the "styles" notepad. Can you help me make the image static?
**Hardware/Software**
- iPhone: ex: 10 XS
- iOS: 14.0.1
- Apple Watch: ex: Series 4 40mm
- watchOS: 6.2.8
- Windows: Windows 10

**Comment by Rexios80** [comment]
You have to disable it in the config file

{
  "animateHeartRateImage": "false"
}

**Comment by Rexios80** [comment]
I just released an iOS app that has a config file generator. You can get it from the iOS App Store. It should make it a lot easier to make config files.
