### ISSUE TITLE
Heart Rate and Calories don't show on localhost:8080 or after running start.bat

### ISSUE THREAD

**Issue by NulChaos** [Rexios80/Health-Data-Server-Overlay#4]
Running start.bat only prints 
"node ./public/app.js
Listening at port 8080
Client connected"

**Comment by Rexios80** [comment]
If you aren’t seeing any heart rate or calorie data being printed to the console then the watch data isn’t getting received. Make sure you have the IP address and port inputted correctly on the watch and that the watch is on the same network as the device you are tying to receive the data on.
