### ISSUE TITLE
How do you remove the calories and the heart image?

### ISSUE THREAD

**Issue by antlepore** [Rexios80/Health-Data-Server-Overlay#40]
I'm not good with coding and everytime I try to mess around in the .json file I end up crashing the application

**Comment by Rexios80** [comment]
This sounds like something you would need to do in Custom CSS. Can I have more details on what you want to do?

**Comment by Rexios80** [comment]
I wrote an iOS app that has a Custom CSS editor. You can get it from the App Store. One of the customization options is disabling the images.
