### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by beaudamion** [Rexios80/Health-Data-Server-Overlay#41]
I have an Elgato Stream Deck that I'm now using to open your app. I used to be able to open via a basic shortcut with run: minimized but the stream deck just goes to the target.exe. Could you add an argument to the app to support -min to so the app starts minimized?

**Comment by Rexios80** [comment]
Can you make a batch script with the following contents and point the stream deck at that?

`start /min "" HDS-Overlay-win.exe`

**Comment by beaudamion** [comment]
Some reason just running it that way it wouldn't start minimized. I have it running minimized another way now. Just too many windows open for vr/mixedreality/games/streaming... lol Thanks though.
