### ISSUE TITLE
Server getting new data format

### ISSUE THREAD

**Issue by wlvstv** [Rexios80/Health-Data-Server-Overlay#43]
Recently the payload being sent to my external server via websocket has changed. the new format is an array object that looks as follows:
`motion:[0.00008393203218777974,0.001005236804485321,0.004633555809656779]`
is this intended behavior? something I need to reconfigure on my end?

Thanks.

**Comment by Rexios80** [comment]
What format are you expecting? I don't think I changed it.

**Comment by wlvstv** [comment]
I am expecting something more aligned with 
`heartRate:xx`
 which is how I was previously processing the information that was being sent over the socket

**Comment by Rexios80** [comment]
Motion is a separate metric you can turn on. If you're getting motion and nothing else it sounds like you need to check the health permissions for the app on the watch.

**Comment by wlvstv** [comment]
sounds good, I'll make sure everything is in the right permissions

**Comment by Rexios80** [comment]
Did you get this figured out?

**Comment by Rexios80** [comment]
Let me know if you need more help
