### ISSUE TITLE
Secure websocket?

### ISSUE THREAD

**Issue by haugli92** [Rexios80/Health-Data-Server-Overlay#44]
Is it possible to implement a config attribute to use WSS instead of WS?

Im transferring data between servers and would like to use encrypted connection.

**Comment by Rexios80** [comment]
On which side? Web or server? Are you using https as well?

**Comment by Rexios80** [comment]
The reason this might be difficult is dealing with certificates. If you have any ideas how to deal with that I'm open.

**Comment by Rexios80** [comment]
Let me know if you want to pursue this further
