### ISSUE TITLE
Discord RPC cannot be disabled

### ISSUE THREAD

**Issue by Ponjimon** [Rexios80/Health-Data-Server-Overlay#45]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes

**Hardware/Software**
- iPhone: ex: 11 Pro
- iOS: latest
- Apple Watch: ex: Series 4 44mm
- watchOS: latest
- Windows: Windows 10
- App: latest
- Server: latest

**To Reproduce**
1. Disable Discord RPC in iPhone app
2. Discord RPC is still active even after restarting the Windows app

**Expected behavior**
Discord RPC should not be active

**Comment by Rexios80** [comment]
You need to put the config file in the same folder as the overlay executable. The help section in the phone app explains this.

**Comment by Ponjimon** [comment]
That explains the export functionality. Sorry, my bad then! Would be nice if the app can tell the overaly program that RPC should be disabled. Consider this a feature request then :) 

Thanks for the fast reply!
