### ISSUE TITLE
When I open HDS Overlay on my windows PC at the top above my IP it says "no files found"

### ISSUE THREAD

**Issue by mikefit403** [Rexios80/Health-Data-Server-Overlay#49]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes/No (If you say no please provide an explanation)

YES

**Hardware/Software**
- iPhone: ex: 11 Pro Max
- iOS: ex: 13.5.1 (if you are on a beta please specify)
- Apple Watch: ex: Series 5 44mm LTE
- watchOS: ex: 6.2.6 (if you are on a beta please specify)
- Windows: ex: Windows 10 2004 (if you are on a beta please specify)
- App: ex: 2.1
- Server: ex: 3.0

When I open HDS Overlay on my windows PC at the top above my IP it says

No hrImage file found
No calImage file found
No beatSound file found

Not sure why? I am using an Apple Watch Series 6 with SLOBS with HDS Overlay 9.30

Thank you for your time.

**Comment by pilo1337** [comment]
if you havent any graphics along the application, this is correct.
It is used for custom graphics. 
Does the HDS works as expected?

**Comment by Rexios80** [comment]
That just means it can't find any custom image files. If you aren't trying to use custom images, it's not an issue.

**Comment by mikefit403** [comment]
Thank you guys for the quick replies. It is working but every one in a while it disconnected when my Apple Watch screen goes dark. I have to raise it back to my wrist to reconnect

**Comment by mikefit403** [comment]
Sorry, this happens when I’m live using SLOBS

**Comment by Rexios80** [comment]
The screen going dark shouldn't affect the app since it's running a workout session. If you are having connections issues it's probably something with your network.

**Comment by pilo1337** [comment]
maybe some sort of energy save mode in the watch? idk if this actually exists, but can be a problem

**Comment by Rexios80** [comment]
There is a setting for workout power saving, but heart rate wouldn't work if it was on.

**Comment by mikefit403** [comment]
Thanks guys. I’ll have a look but really do appreciate your insight
