### ISSUE TITLE
hrMinMax stops working properly when heartrate goes over 100bpm.

### ISSUE THREAD

**Issue by Schakb** [Rexios80/Health-Data-Server-Overlay#50]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes

**Hardware/Software**
- iPhone: 7 plus
- iOS: 14.4.2
- Apple Watch: series 6 Nike edition 44mm
- watchOS: 7.3.3
- Windows: Windows 10 Pro
- App: 8.6 (1)
- Server: ?

**To Reproduce**
1. Enable .hrMinMax and .hrAverage using the app on the iPhone and put the code into OBS.
2. Load everything into OBS. 
3. Get a heartrate lower than 100bmp.
4. Get a heartrate higher than 100bmp.

**Expected behavior**
It should show now the lowest recorded heartrate 101 and the highest recorded heartrate 98/99.
What the issue that I am trying to explain is that for some reason the app thinks that my heartrate of for example 101bpm is very low. 
From this point forward it will ignore any other bpm it encounters as the hrMin won't go lower than 101/100. 

**Screenshots**
[https://i.gyazo.com/6df2f200fad48496effcad66aa6e0cfa.png](https://i.gyazo.com/6df2f200fad48496effcad66aa6e0cfa.png)
[https://i.gyazo.com/2d542dc5358c2ad9b1d051938e7d4f3f.png](https://i.gyazo.com/2d542dc5358c2ad9b1d051938e7d4f3f.png)

**Additional context**
This is the code I created in the app on the iPhone.
```
.hrText::after {
    content: "bpm";
    font-size: 40%;
}
.calText::after {
    content: "cal";
    font-size: 25%;
}
.dataDisplay {
    font-family: 'Monaco', sans-serif;
    text-shadow: 0 0 2px black;
}
.hrText, .calText {
    font-size: 600%;
    margin-top: 5px;
}
.cal {
    left: 340px;
}
.hrMinMax {
    display: flex;
}
.hrAverage {
    display: inline;
}
```

**Comment by Rexios80** [comment]
I'll have to look into it. I noticed some weird behavior but I wasn't able to reproduce it.

**Comment by Schakb** [comment]
I can easily recreate the whole thing as my heartrate likes to go skyrocket sometimes for no reason. I could try and record a small video on how to properly recreate it

**Comment by Rexios80** [comment]
Try this: https://github.com/Rexios80/Health-Data-Server-Overlay/actions/runs/741552617

**Comment by Schakb** [comment]
It works like a charmmmmm now https://streamable.com/o5391x
Thanks a lot Rexios and also piLo1337 :)))))
Have a beautifullll day
