### ISSUE TITLE
Possible integration with Discord?

### ISSUE THREAD

**Issue by kodxana** [Rexios80/Health-Data-Server-Overlay#6]
Can we get integration with discord rich presence?

**Comment by kodxana** [comment]
https://discord.com/rich-presence

**Comment by Rexios80** [comment]
You just want to have it show that you have the overlay open or you want it to actually show the heart rate value?

**Comment by kodxana** [comment]
![image](https://user-images.githubusercontent.com/16674412/83954876-42823880-a84d-11ea-9aea-83c63771ffd5.jpeg) example instead of paying game it will display HR: value

**Comment by Rexios80** [comment]
I’ll look into it. It could be a nice form of passive advertisement.

**Comment by Rexios80** [comment]
This was surprisingly easy to implement. I just made a new release with this feature. Let me know if you have any feedback.

The application image isn't showing yet, but that's just because of how Discord caches the images. If it doesn't show up within a day or two I'll look into it.
