### ISSUE TITLE
Distance traveled doesn't show decimals

### ISSUE THREAD

**Issue by christran** [Rexios80/Health-Data-Server-Overlay#60]
I'm converting the distance traveled from feet to miles with a scale factor of 0.00018939393

But anything less than 1 mile shows up as 0 because the decimals aren't shown.
Could you add a decimals option just like how the speed data has that option.

**Comment by Rexios80** [comment]
Done. Also it's in meters not feet.

**Comment by Rexios80** [comment]
I added the default units to the widget selector to make it more transparent
