### ISSUE TITLE
HDS isn't submitting workout to fitness app since iOS/watchOS update.

### ISSUE THREAD

**Issue by beaudamion** [Rexios80/Health-Data-Server-Overlay#61]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes/No (If you say no please provide an explanation)

YES

**Hardware/Software**
- iPhone: ex: iPhone 12 Pro
- iOS: ex: 15.0
- Apple Watch: ex: Series 5 44mm
- watchOS: ex: 8.0
- Windows: ex: Windows 10 Pro 21H1
- App: ex: 11.6 (1)
- Server: ex: 11.0.0+8

**To Reproduce**
Turn on and do workout...
Turn off and look in activity summary workout is not there.
(Activity Type is set to Fitness Gaming)

**Expected behavior**
Prior to update it would have a workout stored in health / Fitness Activity App and update Daily workout / cal burn.

**Comment by Rexios80** [comment]
Turn on calories and it will save

**Comment by beaudamion** [comment]
Calories is on. It just seemed to stop after the update.

**Comment by Rexios80** [comment]
Oh it stopped saving after updating to watchOS 8?

**Comment by beaudamion** [comment]
Yes. worked before watchOS / iOS update.. first time running it again since update and now it doesn't seem to save the workout.

**Comment by beaudamion** [comment]
AND never mind... for some reason.. after I open up the Default Fitness app.. ran a workout for like 2 minutes and ended it.. the workout from your app just got pushed and showed up.. Weird.
