### ISSUE TITLE
Increase heart rate update interval?

### ISSUE THREAD

**Issue by kingrun** [Rexios80/Health-Data-Server-Overlay#8]
Sometimes it seems like it's not updating that fast. I sometimes get 8 calorie updates before I get a heart update. Is there anyway to increase the interval at which it pulls this data? Or is that limited to the apple watch itself?

**Comment by Rexios80** [comment]
The watch is sending data as soon as it gets it. watchOS does throttle REST calls so maybe that’s part of the problem, but I also think it just gets calorie updates more frequently.
