### ISSUE TITLE
system32 No license field

### ISSUE THREAD

**Issue by snugglestream** [Rexios80/Health-Data-Server-Overlay#9]
Hello - firstly thank you for making this software!

I'm having an issue running the program: I've followed the steps in the description, but when running the setup batch file I get the following dialogue in the cmd window (when running as Administrator):

C:\WINDOWS\system32>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

[        ..........] \ prepare:system32: WARN system32 No license field. 

When not running as administrator, I get this:

C:\Program Files\HealthDataServer\2\Health-Data-Server-Overlay-2.1.1>npm install
npm WARN apple-watch-health-data-server@1.0.0 No repository field.
npm WARN apple-watch-health-data-server@1.0.0 No license field.

npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files\HealthDataServer\2\Health-Data-Server-Overlay-2.1.1\node_modules
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\HealthDataServer\2\Health-Data-Server-Overlay-2.1.1\node_modules'
npm ERR!  [OperationalError: EPERM: operation not permitted, mkdir 'C:\Program Files\HealthDataServer\2\Health-Data-Server-Overlay-2.1.1\node_modules'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\HealthDataServer\2\Health-Data-Server-Overlay-2.1.1\node_modules'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'mkdir',
npm ERR!     path: 'C:\\Program Files\\HealthDataServer\\2\\Health-Data-Server-Overlay-2.1.1\\node_modules'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\HealthDataServer\\2\\Health-Data-Server-Overlay-2.1.1\\node_modules',
npm ERR!   parent: 'Health-Data-Server-Overlay-2.1.1'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

Running the start batch file does nothing (flicks up the cmd window for less than a second before disappearing).

I have node.js and Git installed.

Please let me know if I can provide any additional information to help figure out the issue.

Thank you!

**Comment by Rexios80** [comment]
Did you move any of the files around? It looks like it’s not running in the right place.

**Comment by snugglestream** [comment]
Hiya, SO initially I extracted to programme files - but after you responded I deleted it completely and reinstalled to desktop. It then ran perfectly but my watch stopped picking up my heart beat so i restarted the watch and tried again with no luck.  I then deleted it again - made sure i had the right version of node and the watch started working again but now the start batch file won't run.

**Comment by Rexios80** [comment]
Can you check to make sure the watch app has the HealthKit permissions it needs?

Also restarting the watch might not actually kill the app completely. You can try this: https://support.apple.com/en-us/HT201398

**Comment by Rexios80** [comment]
Did you make sure you ran the setup script first? If that doesn't work, try running the start script from the command line so that you can see the error it prints out. It probably looks like it isn't running because it prints the error and closes so quickly you can't see it.

**Comment by Rexios80** [comment]
If you need more help on this, feel free to reopen the issue. I compiled a list of troubleshooting steps in the Wiki. Maybe try those out if you still can't get it working.
